services:

  servidor-web:
    build: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/

  # Definimos el servicio para la Base de Datos MySQL 
  base-datos:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfgDAW2526
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d