### PUT request with an existing user
PUT http://localhost:8080/users/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NzQ0NDgxMjYsImV4cCI6MTc3NDQ1NTMyNiwiZGF0YSI6eyJ1c2VyX2lkIjoyLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIn19.A2o_g7aRBodmCPdAl87jddcq6ioteFZufv9oG44uYWk

{
  "email": "usertest@example.com",
  "password": "1234abcd",
  "avatar_url": "hola.png"
}
###