### POST request to create a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "1234abcd",
  "role": "admin",
  "restaurant_id": 1,
  "avatar_url": ""
}
###