### GET request to example server
GET http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NzQ2MTYxNTMsImV4cCI6MTc3NDYyMzM1MywiZGF0YSI6eyJ1c2VyX2lkIjoyLCJlbWFpbCI6InVzZXJ0ZXN0QGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIn19.uScMjcw5aSw5Efo79J3Ml7tZikqrDu-s0yqbaKRaaU4

###