### 1. Iniciar sesión (Login)
# Guardamos el token que nos devuelve en una variable global de PhpStorm
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "",
  "password": "tu_contraseña"
}

> {%
    // Este pequeño script de PhpStorm captura el token del JSON de respuesta
    client.global.set("auth_token", response.body.token);
    client.log("Token guardado con éxito: " + response.body.token);
%}